dist: xenial
language: python
python:
  - "3.6"
  - "3.8"
  - "pypy"

install:
  # install python requirements
  - pip install coveralls
  - pip install -e .[tests]

script:
  # finally run tests
  - make ci-test

after_success:
  - coveralls
